module.exports = {
  bot: 'Coffy ☕',
  botID: '774912954403127347',
  token: 'Nzc0OTEyOTU0NDAzMTI3MzQ3.X6er7Q.wZ08q4feSI_PZxy2iBSvwu-9r8Y',
  mongo: 'La conexión a mongodb',
  prefix: 'El prefijo "default" de tu bot',
  yandexAPIkey: 'Yandex token',
  dankMemer: 'dankMemer token',
  weezKey: 'Weez token',
  dblKey: 'DBL token',
  dblSkey: 'DBL key',
  owners: ['Las ID de los owners'],
  support: 'La invitación al servidor de soporte',
  invite: 'https://discord.com/api/oauth2/authorize?client_id=774912954403127347&permissions=8&scope=bot',
  dbl: '',
  vote: '',
  banner: '',
  github: '',
  donate: '',
  logs: {
    token: '',
    id: '',
  },
  votes: {
    token: '',
    id: '',
  },
};
